### ISSUE TITLE
Allow Bot Initiation without Comments

### ISSUE THREAD

**Issue by ap0l0** [fpedrolucas95/Instagram-Bot#3]
You can't initiate the bot unless you type something on the "comments section" even when comments are disabled.

I need to type "a" and then click initiate even when the comments are disable. 

<img width="239" alt="image" src="https://github.com/fpedrolucas95/Instagram-Bot/assets/14894967/19f1ab5e-4360-4352-9307-8a4b2398ff2e">

**Comment by fpedrolucas95** [comment]
Hi @ap0l0 ,

Thanks for pointing out this issue. It was a known bug, and I'm sorry for any inconvenience it may have caused. The "Enable Comments" button should have been controlling the need for comments and allowing the bot to initiate even when comments are disabled.

I'm happy to let you know that this problem has been fixed in both branches. Now, you won't need to type anything in the "comments section" when comments are disabled to initiate the bot.

**Comment by ap0l0** [comment]
just saw this fix, way easier now to use!
